// client/src/components/FoodForm/FoodItemServingSize.tsx
import React from "react";

type FoodItemServingSizeProps = {
  servingSizes: string[];
  onSelectSize: (selectedSize: string) => void;
};

function FoodItemServingSize({ servingSizes, onSelectSize }: FoodItemServingSizeProps) {
  function handleSizeChange(event: React.ChangeEvent<HTMLSelectElement>) {
    const selectedSize = event.target.value;
    onSelectSize(selectedSize);
  }

  return (
    <div>
      <select onChange={handleSizeChange}>
        <option value="">-- Select serving size --</option>
        {servingSizes.map((size) => (
          <option key={size} value={size}>
            {size}
          </option>
        ))}
      </select>
    </div>
  );
}

export default FoodItemServingSize;

// healthy-web/src/components/FoodEntry/FoodItemServingSize.vue
<script setup lang="ts">
const props = defineProps<{
  servingSizes: string[];
}>();
</script>

<template>
  <div>
    <select name="serving-size">
      <option value=""></option>
      <option v-for="servingSize in servingSizes" value="servingSize">
        {{ servingSize }}
      </option>
    </select>
  </div>
</template>
